# Week 1 assignments

This notebook contains the implementation of the LAFF week 1 homework. Initially targeting the MatScript language (Matlab), I chose to use python 3 instead.

### Homework 1.5.2.1
1/1 point (graded)

Implement the function laff_copy that copies a vector into another vector. The function is defined as
```
function [ y_out ] = laff_copy( x, y )
```
where

`x` and `y` must each be either an n×1 array (column vector) or a 1×n array (row vector);

`y_out` must be the same kind of vector as `y` (in other words, if `y` is a column vector, so is `y_out` and if `y` is a row vector, so is `y_out`).

The function should “transpose" the vector if `x` and `y` do not have the same “shape" (if one is a column vector and the other one is a row vector).

If `x` and/or `y` are not vectors or if the size of (row or column) vector `x` does not match the size of (row or column) vector `y`, the output should be 'FAILED'.

In [70]:
import numpy as np

%pdb on
def laff_copy(x, y):
    '''
        Copy one vector into another of shape y
    '''
    if x.shape != y.shape and x.shape != y.T.shape: # Ensure they have the same size
        return 'FAILED'
    else:
        if x.shape != y.shape: # Then the copy is between a row and a column vector
            x = numpy.copy(x.T) # Numpy.copy very important or the last test fails
        
        if y.shape[0] == 1: # y is a row vector
            for i in range(y.shape[1]):
                x[0][i] = y[0][i]
        else:
            for i in range(y.shape[0]):
                x[i][0] = y[i][0]
        return x
    
    
# Tests
x = np.ndarray(shape=(1, 4), dtype=int, buffer=np.array([5, 2, 8, 1])) # row vector
x_2 = np.ndarray(shape=(1, 5), dtype=int, buffer=np.array([5, 8, 1, 7, 9])) # row vector
x_3 = np.ndarray(shape=(1, 5), dtype=int, buffer=np.array([1, 2, 3, 4, 5])) # row vector
y = np.ndarray(shape=(4, 1), dtype=int, 
               buffer=np.array([[4], # column vector
                                [6],
                                [9],
                                [23]
                                    ]))

y_2 = np.ndarray(shape=(5, 1), dtype=int, 
               buffer=np.array([[4], # column vector
                                [6],
                                [9],
                                [23],
                                [2]
                                    ]))

y_3 = np.ndarray(shape=(5, 1), dtype=int, 
               buffer=np.array([[1], # column vector
                                [2],
                                [3],
                                [4],
                                [5]
                                    ]))

print(laff_copy(x, x_2) == 'FAILED')
print(laff_copy(x, y_2) == 'FAILED')
print('-----------------')
print(laff_copy(x_2, x_3))
print(laff_copy(y_2, y_3))
print('-----------------')
print(laff_copy(x, y))
print(laff_copy(y, x))

Automatic pdb calling has been turned ON
True
True
-----------------
[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]
-----------------
[[ 4]
 [ 6]
 [ 9]
 [23]]
[[5 2 8 1]]


### Homework 1.5.3.1
1/1 point (graded)
Implement the function laff_scal that scales a vector x by a scalar α. The function is defined as

```
function [ x_out ] = laff_scal( alpha, x )
```

where

`x` must be either an n×1 array (column vector) or a 1×n array (row vector);

`x_out` must be the same kind of vector as x; and

If `x` or alpha are not a (row or column) vector and scalar, respectively, the output should be 'FAILED'.

Check your implementation with the script in  LAFF-2.0xM/Programming/Week01/test_scal.m.